apiVersion: v1
kind: Service
metadata:
  name: zenodo-es
  labels:
    app: zenodo
spec:
  ports:
    - port: 9200
      name: es1
    - port: 9300
      name: es2
  selector:
    app: zenodo
    tier: es
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zenodo-es
  labels:
    app: zenodo
spec:
  selector:
    matchLabels:
      app: zenodo
      tier: es
  serviceName: zenodo-es
  template:
    metadata:
      labels:
        app: zenodo
        tier: es
    spec:
      volumes:
        - name: es-pv-storage
          persistentVolumeClaim:
            claimName: zenodo-es-pv-claim
      containers:
      - name: es
        image: elasticsearch:2.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        command: ["/bin/sh"]
        args: ["-c", "plugin install royrusso/elasticsearch-HQ/v2.0.3; plugin install mapper-attachments; /docker-entrypoint.sh elasticsearch"]
        volumeMounts:
        - name: es-pv-storage
          mountPath: /usr/share/elasticsearch/data