apiVersion: v1
kind: Service
metadata:
  name: zenodo-mq
  labels:
    app: zenodo
spec:
  ports:
    - port: 15672
      name: mq1
    - port: 5672
      name: mq2
  selector:
    app: zenodo
    tier: mq
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenodo-mq
  labels:
    app: zenodo
spec:
  selector:
    matchLabels:
      app: zenodo
      tier: mq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zenodo
        tier: mq
    spec:
      containers:
      - name: mq
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
        - containerPort: 5672