kind: PersistentVolume
apiVersion: v1
metadata:
  name: zenodo-es-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: remote
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare/elasticsearch
    server: 10.250.27.253
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zenodo-es-pv-claim
  labels:
    type: es-storage
spec:
  storageClassName: remote
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zenodo-postgres-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: remote
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare/db
    server: 10.250.27.253
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zenodo-postgres-pv-claim
  labels:
    type: db-storage
spec:
  storageClassName: remote
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zenodo-archive-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: remote
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare/archive
    server: 10.250.27.253
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zenodo-archive-pv-claim
  labels:
    type: archive-storage
spec:
  storageClassName: remote
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800G
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zenodo-data-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: remote
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare/data
    server: 10.250.27.253
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zenodo-html-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: remote
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare/html
    server: 10.250.27.253
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zenodo-html-pv-claim
  labels:
    type: html-storage
spec:
  storageClassName: remote
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zenodo-data-pv-claim
  labels:
    type: data-storage
spec:
  storageClassName: remote
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: remote
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare/backup
    server: 10.250.27.253
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-pv-claim
  labels:
    type: backup-storage
spec:
  storageClassName: remote
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi