apiVersion: v1
kind: Service
metadata:
  name: zenodo-frontend
  labels:
    app: zenodo
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: zenodo
    tier: frontend
  externalIPs:
  - 10.250.27.254
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenodo-frontend
  labels:
    app: zenodo
spec:
  selector:
    matchLabels:
      app: zenodo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zenodo
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: infnct/zenodo
        volumeMounts:
        - name: zenodo-config-file
          mountPath: /opt/zenodo_venv/var/instance
        - name: zenodo-httpd-cert-files
          mountPath: /opt/httpd-config/certs
        ports:
        - containerPort: 5601
      volumes:
      - name: zenodo-config-file
        configMap:
          name: zenodo-config
      - name: zenodo-httpd-cert-files
        secret:
          secretName: httpd-certs