apiVersion: v1
kind: Service
metadata:
  name: zenodo-worker
  labels:
    app: zenodo
spec:
  ports:
    - port: 5601
  selector:
    app: zenodo
    tier: worker
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenodo-worker
  labels:
    app: zenodo
spec:
  selector:
    matchLabels:
      app: zenodo
      tier: worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zenodo
        tier: worker
    spec:
      containers:
      - name: worker
        image: infnct/zenodo
        volumeMounts:
        - name: zenodo-config-file
          mountPath: /opt/zenodo_venv/var/instance
        ports:
        - containerPort: 5601
        command: ["/bin/sh"]
        args: ["-c", "source /opt/zenodo_venv/bin/activate; celery worker -A zenodo.celery --loglevel=INFO"]
      volumes:
      - name: zenodo-config-file
        configMap:
          name: zenodo-config