apiVersion: v1
kind: Service
metadata:
  name: zenodo-frontend
  labels:
    app: zenodo
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: zenodo
    tier: frontend
  externalIPs:
  - 10.250.27.254
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenodo-frontend
  labels:
    app: zenodo
spec:
  selector:
    matchLabels:
      app: zenodo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zenodo
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: infnct/zenodo:1.0.6
        volumeMounts:
        - name: zenodo-archive-storage
          mountPath: /opt/zenodo_venv/var/instance/archive
        - name: zenodo-data-storage
          mountPath: /opt/zenodo_venv/var/instance/data
        - name: zenodo-config-file
          mountPath: /opt/invenio-config
        - name: zenodo-httpd-cert-files
          mountPath: /opt/httpd-config/certs
        - name: zenodo-shibboleth-config-files
          mountPath: /opt/shibboleth-config
        - name: zenodo-html-files
          mountPath: /var/www/html
        ports:
        - containerPort: 5601
      volumes:
      - name: zenodo-archive-storage
        persistentVolumeClaim:
          claimName: zenodo-archive-pv-claim
      - name: zenodo-data-storage
        persistentVolumeClaim:
          claimName: zenodo-data-pv-claim
      - name: zenodo-html-files
        persistentVolumeClaim:
          claimName: zenodo-html-pv-claim
      - name: zenodo-config-file
        configMap:
          name: zenodo-config
      - name: zenodo-httpd-cert-files
        secret:
          secretName: httpd-certs
      - name: zenodo-shibboleth-config-files
        secret:
          secretName: shibboleth-conf
