apiVersion: v1
kind: ConfigMap
metadata:
  name: zenodo-config
data:
  invenio.cfg: |
    ACCOUNTS_SESSION_REDIS_URL = "redis://zenodo-redis:6379/2"
    BROKER_URL = "amqp://guest:guest@zenodo-mq:5672//"
    CELERY_BROKER_URL = "amqp://guest:guest@zenodo-mq:5672//"
    CELERY_BROKER_URL = "amqp://guest:guest@zenodo-mq:5672//"
    CACHE_REDIS_URL = "redis://zenodo-redis:6379/0"
    CACHE_TYPE = "redis"
    CELERY_RESULT_BACKEND = "redis://zenodo-redis:6379/1"
    SEARCH_ELASTIC_HOSTS = "[zenodo-es]"
    SECRET_KEY = "V3ryDifficultP@ssw0rd"
    SESSION_COOKIE_SECURE = "True"
    SQLALCHEMY_DATABASE_URI = "postgresql://zenodo:zenodo@zenodo-postgres/zenodo"
    REDIS_URL = "postgresql://zenodo:zenodo@zenodo-postgres/zenodo"
